wezvabackendapp:
  image:
    repository: public.ecr.aws/nginx/nginx
    tag: latest
backendSvc:
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
mysqlCreds:
  database: "mywezvadb"
  password: "password"
  rootpassword: "password"
  username: "wezvatech"
